# Generated by Django 4.2.11 on 2024-04-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="商品名称")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="价格(元)",
                    ),
                ),
                ("num", models.IntegerField(verbose_name="购买数量")),
                ("unit", models.CharField(max_length=32, verbose_name="每件商品单位")),
                (
                    "order_time",
                    models.CharField(max_length=32, verbose_name="下单时间"),
                ),
                ("order_id", models.CharField(max_length=64, verbose_name="订单编号")),
                (
                    "buyer_address",
                    models.CharField(max_length=64, verbose_name="买方收货地址"),
                ),
                (
                    "buyer_telephone",
                    models.CharField(max_length=32, verbose_name="买方手机号码"),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserInfo_broker",
                        to="rbac.userinfo",
                        verbose_name="卖家",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserInfo_buyer",
                        to="rbac.userinfo",
                        verbose_name="消费者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="商品名称")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="价格(元)",
                    ),
                ),
                ("num", models.IntegerField(verbose_name="库存数量")),
                ("unit", models.CharField(max_length=32, verbose_name="每件商品单位")),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rbac.userinfo",
                        verbose_name="卖家",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="商品名称")),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[
                            (1, "蔬菜"),
                            (2, "肉制品"),
                            (3, "水果"),
                            (4, "零食"),
                            (5, "方便速食"),
                            (6, "奶制品"),
                            (7, "饮料"),
                            (8, "纸巾"),
                            (9, "酒类饮品"),
                            (10, "洗浴用品"),
                            (11, "一般药品"),
                            (12, "果干"),
                            (13, "清洁工具"),
                            (14, "数码设备"),
                            (15, "手机配件"),
                            (16, "美妆"),
                            (17, "服饰"),
                            (18, "保健品"),
                            (19, "母婴用品"),
                            (20, "其他"),
                        ],
                        verbose_name="商品类别",
                    ),
                ),
                ("num", models.IntegerField(verbose_name="需求数量")),
                ("unit", models.CharField(max_length=32, verbose_name="每件商品单位")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rbac.userinfo",
                        verbose_name="消费者",
                    ),
                ),
            ],
        ),
    ]
