# Generated by Django 4.2.11 on 2024-04-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                ("url", models.CharField(max_length=128, verbose_name="含正则的URL")),
                (
                    "is_menu",
                    models.BooleanField(default=False, verbose_name="是否可做菜单"),
                ),
                ("icon", models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="角色名称")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="rbac.permission", verbose_name="拥有的所有权限"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "telephone",
                    models.CharField(default=0, max_length=32, verbose_name="手机号码"),
                ),
                (
                    "address",
                    models.CharField(
                        default="未填写", max_length=64, verbose_name="地址"
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, to="rbac.role", verbose_name="身份"
                    ),
                ),
            ],
        ),
    ]
